services:
  db:
    image: postgres:16
   # expose:
    #  - "5433:5432"  
    ports:
      - "5433:5432"
    environment:
       - POSTGRES_USER=dbuser
       - POSTGRES_PASSWORD=pass123
       - POSTGRES_DB=devops_db

    healthcheck:

      test: 
       - CMD-SHELL
       - pg_isready -U dbuser
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    volumes:
      - 'dslabdb:/var/lib/postgresql/data/'

  spring:
      image: ghcr.io/klewnk/spring-app:latest # Χρησιμοποίησε το πλήρες όνομα του image  #   image: db
      # build: ... (μπορείς να το σβήσεις στο VM, το build γίνεται στον Jenkins)
      build:
        context: .
        dockerfile: nonroot-multistage.Dockerfile
      ports:
       - "8081:8080"
      depends_on:
        db:
          condition: service_healthy 
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/devops_db
        - SPRING_DATASOURCE_USERNAME=dbuser
        - SPRING_DATASOURCE_PASSWORD=pass123
      healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
         interval: 30s
         timeout: 30s
         retries: 3


  frontend:
       image: ghcr.io/klewnk/my-frontend:latest
       ports:
          - "80:80"
       depends_on:
        backend:
             condition: service_healthy # Το Frontend θα ξεκινήσει ΜΟΝΟ αν το backend είναι UP

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" # SMTP port 
      - "8025:8025" # Web UI
      
volumes:
  dslabdb: