services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=devops_db
    volumes:
      - pgdata_docker:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d devops_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  app:
    image: ghcr.io/klewnk/spring-app:latest
    container_name: spring_app_container
    restart: always
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
      mailhog: 
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/devops_db
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=pass123
      - SPRING_MAIL_HOST=mailhog
      - SPRING_MAIL_PORT=1025
    networks:
      - app-network

  web:
    image: nginx:alpine
    container_name: nginx_container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_container
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - app-network



  admin-dashboard:
    build:
      context: .
      dockerfile: metabase.Dockerfile
    container_name: metabase_container
    restart: always
    ports:
      - "3001:3000" # Θα μπαίνεις από το http://34.51.255.13:3001
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=devops_db     # <--- Βάλε το όνομα της βάσης σου
      - MB_DB_PORT=5432
      - MB_DB_USER=dbuser            # <--- Το username της Postgres σου
      - MB_DB_PASS=pass123        # <--- Το password της Postgres σου
      - MB_DB_HOST=db              # Το όνομα του service της βάσης
    networks:
      - app-network

  user-management:
    build:
      context: .
      dockerfile: pocketbase.Dockerfile
    container_name: pocketbase_container
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb/pb_data
    networks:
      - app-network

  keycloak:
    build:
      context: .
      dockerfile: Keycloak.Dockerfile
    container_name: keycloak_container
    environment:
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KC_HTTP_RELATIVE_PATH=/auth
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    # ΜΗΝ βάλεις ports: - "8180:8080" εδώ. 
    # Θέλουμε όλο το traffic να περνάει ΜΟΝΟ από τον Nginx (port 80).
    networks:
      - app-network

volumes:
  pgdata_docker:

networks:
  app-network:
    driver: bridge