services:
  # 1. ΒΑΣΗ ΔΕΔΟΜΕΝΩΝ (PostgreSQL)
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    # Δεν χρειάζεται ports αν δεν θέλεις να μπαίνεις από έξω με DBeaver
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=devops_db
    volumes:
      - pgdata_docker:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d devops_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Η SPRING ΕΦΑΡΜΟΓΗ
  app:
    image: ghcr.io/klewnk/spring-app:latest
    container_name: spring_app_container
    restart: always
    # Αφαιρούμε το "8080:8080" από τα ports για να περνάνε όλοι από τον Nginx
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/devops_db
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=pass123
      - SPRING_MAIL_HOST=mailhog
      - SPRING_MAIL_PORT=1025

  # 3. REVERSE PROXY (Nginx) - Για την πόρτα 80
  web:
    image: nginx:alpine
    container_name: nginx_container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  # 4. DATABASE UI (Adminer)
  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - "8081:8080"
    depends_on:
      - db

  # 5. EMAIL SERVER (MailHog)
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_container
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  pgdata_docker: