server {
    listen 80;
    server_name klewn-devops.duckdns.org;
    return 301 https://$host$request_uri; # Redirect σε HTTPS
}

server {
    listen 443 ssl;
    server_name klewn-devops.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/klewn-devops.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/klewn-devops.duckdns.org/privkey.pem;

    location / {
        proxy_pass http://spring_app_container:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /mail/ {
    proxy_pass http://mailhog:8025/;
     }


   location /db/ {
    proxy_pass http://adminer:8081/;
    proxy_set_header Host $host;
}
}
