apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    # Αφαιρέσαμε το rewrite-target γιατί μπέρδευε τα paths
    # Αν χρειαστείς rewrite για adminer, θέλει regex (πιο σύνθετο)
spec:
  # Λέμε στο MicroK8s να το διαχειριστεί αυτό
  ingressClassName: public
  rules:
  # ΠΡΟΣΟΧΗ: Αυτό πρέπει να είναι ΙΔΙΟ με αυτό που χτυπάει το Jenkins Smoke Test
  - host: klewn-devops.duckdns.org 
    http:
      paths:
      # 1. Spring Boot (Η κύρια εφαρμογή πιάνει τα πάντα)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring-app-service
            port:
              number: 80

      # 2. Adminer (ΠΡΟΣΟΧΗ: Χωρίς rewrite ίσως θέλει ρύθμιση Base URL)
      - path: /adminer
        pathType: Prefix
        backend:
          service:
            name: adminer-service
            port:
              number: 8080

      # 3. MailHog
      - path: /mailhog
        pathType: Prefix
        backend:
          service:
            name: mailhog-service
            port:
              number: 8025