---
- name: Full Setup and Deploy to MicroK8s
  hosts: devops_gcloud1
  become: yes  # Τρέχουμε τα πάντα ως root (sudo)
  vars:
    ansible_user: kleonkola



  tasks:
    - name: Εγκατάσταση εργαλείου fuser (αν λείπει)
      apt:
        name: psmisc
        state: present

    - name: Stop and Remove ALL Docker Containers
      shell: "docker stop $(docker ps -q) || true && docker rm $(docker ps -aq) || true"
      ignore_errors: yes

    - name: Σταμάτημα γνωστών services που δημιουργούν conflicts
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - nginx
        - apache2
        - httpd
        - spring
        - postgresql
      ignore_errors: yes

    - name: Ensure MicroK8s is STARTED
      shell: "/snap/bin/microk8s start"
      register: micro_start
      failed_when: 
        - micro_start.rc != 0 
        - "'already running' not in micro_start.stdout"
      ignore_errors: yes

    - name: Περίμενε 15 δευτερόλεπτα για να σηκωθούν τα services του K8s
      pause:
        seconds: 15



    - name: Βίαιο κλείσιμο διεργασιών στις πόρτες 80, 443, 8080, 8025
      shell: "fuser -k {{ item }}/tcp"
      loop:
        - 80
        - 443
        - 8080
        - 8025
      ignore_errors: yes

    # ---SETUP ---
    
    - name: Εγκατάσταση MicroK8s
      community.general.snap:
        name: microk8s
        classic: yes
        state: present

    - name: Προσθήκη του χρήστη στο group microk8s
      user:
        name: "{{ ansible_user }}"
        groups: microk8s
        append: yes

    - name: Reset SSH Connection (για να πιάσει το νέο group)
      meta: reset_connection

    - name: Ρύθμιση ιδιοκτησίας του φακέλου .kube
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: microk8s
        mode: '0750'

    - name: Ενεργοποίηση Addons
      command: /snap/bin/microk8s enable dns storage ingress
      register: addons_result
      changed_when: "'enabled' in addons_result.stdout"
      ignore_errors: yes

    - name: Αναμονή μέχρι το MicroK8s να είναι έτοιμο
      command: /snap/bin/microk8s status --wait-ready
      changed_when: false

    # --- DEPLOYMENT ---

    - name: Δημιουργία φακέλου project στο VM
      file:
        path: "/home/{{ ansible_user }}/kubernetes"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Μεταφορά των K8s manifests στο VM
      copy:
        src: "{{ playbook_dir }}/{{ item }}"
        dest: "/home/{{ ansible_user }}/kubernetes/{{ item }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
      loop:
        - postgres-k8s.yaml
        - mailhog-k8s.yaml
        - adminer-k8s.yaml
        - app-k8s.yaml
        - ingress-k8s.yaml

    - name: Apply K8s Manifests
      command: /snap/bin/microk8s kubectl apply -f /home/{{ ansible_user }}/kubernetes/{{ item }}
      loop:
        - postgres-k8s.yaml
        - mailhog-k8s.yaml
        - adminer-k8s.yaml
        - app-k8s.yaml
        - ingress-k8s.yaml


    - name: Wait for Pods
      command: "microk8s kubectl wait --for=condition=ready pod -l app=spring-app --timeout=120s"
      
    - name: Smoke Test (Check 200 OK)
      uri:
        url: "http://klewn-devops.duckdns.org"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 20
      delay: 5