---
- name: Install basic packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - software-properties-common
    - curl
    - apt-transport-https
    - ca-certificates

- name: Get Docker GPG key
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  args:
    warn: false

- name: Add Docker PPA
  apt_repository:
    # Χρησιμοποιούμε το {{ ansible_distribution_release }} για να βρει αυτόματα αν είναι focal, jammy, noble κλπ.
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Add existing user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes