- import_playbook: postgres.yaml
  vars:
    ansible_limit: "devops_gcloud1"
- import_playbook: mailhog.yaml
  vars:
    mailhog_version: "v1.0.1"
    mailhog_path: "/opt/mailhog"
    smtp_port: 1025
    public_ip: "127.0.0.1"
    

- import_playbook: spring.yaml