---
- name: Install and Setup PostgreSQL (Native VM Scenario)
  hosts: all
  become: yes
  vars:
    db_name: "devops_db"
    db_user: "dbuser"
    db_password: "pass123"



  tasks:
  
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PostgreSQL and dependencies
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
          - acl
        state: present

    - name: Ensure PostgreSQL service is started and enabled
      service:
        name: postgresql
        state: started
        enabled: yes

    # --- ΡΥΘΜΙΣΗ ΧΡΗΣΤΩΝ & ΒΑΣΗΣ ---
    
    - name: Create database user 'dbuser' with password
      community.postgresql.postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        role_attr_flags: CREATEDB,NOSUPERUSER
      become: yes
      become_user: postgres

    - name: Create database 'devops_db'
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"
        owner: "{{ db_user }}"
      become: yes
      become_user: postgres

    # --- ΡΥΘΜΙΣΗ ΠΡΟΣΒΑΣΗΣ (Δυναμική εύρεση του αρχείου) ---

    - name: Find pg_hba.conf path automatically
      shell: find /etc/postgresql -name pg_hba.conf | head -n 1
      register: pg_config_path
      changed_when: false

    - name: Allow password authentication for localhost
      community.postgresql.postgresql_pg_hba:
        dest: "{{ pg_config_path.stdout }}"  # Χρησιμοποιούμε το path που βρήκαμε
        contype: host
        users: all
        source: 127.0.0.1/32
        method: scram-sha-256  # Πιο σύγχρονο από md5, δουλεύει το ίδιο
        databases: all
      become: yes
      become_user: postgres
      notify: Restart Postgres

  handlers:
    - name: Restart Postgres
      service:
        name: postgresql
        state: restarted