---
- name: Install and Setup PostgreSQL (Native VM Scenario)
  hosts: devops_gcloud1
  become: yes
  vars:
    db_name: "devops_db"
    db_user: "dbuser"
    db_password: "pass123"



  tasks:
    # --- ΕΓΚΑΤΑΣΤΑΣΗ ---
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PostgreSQL and dependencies
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
          - acl
          - psmisc  
        state: present

    # --- ΚΑΘΑΡΙΣΜΟΣ & ΕΚΚΙΝΗΣΗ ---
    - name: Ensure PostgreSQL service is stopped first
      service:
        name: postgresql
        state: stopped

    - name: Kill any process holding port 5432
      shell: "fuser -k 5432/tcp || true"
      ignore_errors: yes

    - name: Ensure PostgreSQL service is started
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Wait for PostgreSQL to be ready
      wait_for:
        port: 5432
        host: 127.0.0.1
        state: started
        timeout: 30

    # --- ΔΗΜΙΟΥΡΓΙΑ ΒΑΣΗΣ & ΧΡΗΣΤΗ ---
    - name: Create database user 'dbuser'
      community.postgresql.postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        role_attr_flags: CREATEDB,NOSUPERUSER
      become: yes
      become_user: postgres

    - name: Create database 'devops_db'
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"
        owner: "{{ db_user }}"
      become: yes
      become_user: postgres

    # --- ΡΥΘΜΙΣΕΙΣ ΔΙΚΤΥΟΥ  ---
    
    - name: Find config file path
      shell: find /etc/postgresql -name postgresql.conf | head -n 1
      register: pg_conf_path
      changed_when: false

    - name: Configure PostgreSQL to listen on all addresses
      lineinfile:
        path: "{{ pg_conf_path.stdout }}"
        regexp: "^#?listen_addresses ="
        line: "listen_addresses = '*'"
        state: present
      become: yes
      notify: Restart Postgres

    - name: Allow connection from Docker (and everywhere)
      community.postgresql.postgresql_pg_hba:
        dest: "{{ pg_conf_path.stdout | replace('postgresql.conf', 'pg_hba.conf') }}"
        contype: host
        users: all
        source: 0.0.0.0/0
        method: scram-sha-256
        databases: all
      become: yes
      become_user: postgres
      notify: Restart Postgres

  handlers:
    - name: Restart Postgres
      service:
        name: postgresql
        state: restarted